GLOBAL_LIST_EMPTY(all_observable_events)
GLOBAL_VAR_INIT(shit_left, 0)
GLOBAL_VAR_INIT(piss_left, 0)
GLOBAL_VAR_INIT(deaths_in_space,0)
GLOBAL_VAR_INIT(total_deaths,0)
GLOBAL_VAR_INIT(total_orgasms,0)
GLOBAL_VAR_INIT(teeth_lost,0)
GLOBAL_LIST_EMPTY(initialTypeIcon)
GLOBAL_LIST_INIT(font_resources, list('fonts/Shage/Shage.ttf', 'fonts/cond.ttf'))
GLOBAL_VAR_INIT(internal_tick_usage, 0.2 * world.tick_lag)